// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnhtpciitjycpqqimgce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuaHRwY2lpdGp5Y3BxcWltZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTE2NTksImV4cCI6MjA2NTUyNzY1OX0.9ZkfiUQ43jLzi-WHeRxX6NB_VvoAvouQvy1o2XO5tdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);